version: '3.7'

services:
  my-backend:
    image: asia.gcr.io/nemo-v-backend/mybackend10-nestjs:0.3
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile.prod
    # volumes:
    #   - ./src:/myfolder/src
    # env_file:
    #   - ./.env.prod
    # ports:
    #   - 3000:3000
# version: '3.7'

# # 컴퓨터들
# services:
#   # 컴퓨터이름
#   my-backend:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     # volumes:
#     #   - ./src:/myfolder/src
#     ports:
#       - 3000:3000
#     env_file:
#       - ./.env.prod

# 컴퓨터이름
# my-database:
# platform: linux/86_64
# image: mysql:latest
# environment:
#   MYSQL_DATABASE: 'mydocker10'
#   MYSQL_ROOT_PASSWORD: 'root'
# ports:
#   - 3306:3306
